application: simplecta
version: 2
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  login: required

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /update/
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required
